import { Question } from "@/types/game";

export const DEFAULT_QUESTIONS: Question[] = [
  {
    id: "q1_relapse_masturbation",
    textMale: "Kya aapne aaj masturbate kiya?",
    textFemale: "Kya aapne aaj masturbate kiya?",
    textMaleEn: "Did you masturbate today?",
    textFemaleEn: "Did you masturbate today?",
    polarity: "slip_on_yes",
    category: "relapse",
    hpDamage: 45,
    xpGain: 35,
    hpHeal: 10,
  },
  {
    id: "q2_watch_explicit",
    textMale: "Kya aapne kuch ganda / inappropriate dekha kya?",
    textFemale: "Kya aapne kuch ganda / inappropriate dekha kya?",
    textMaleEn: "Did you watch anything explicit or inappropriate?",
    textFemaleEn: "Did you watch anything explicit or inappropriate?",
    polarity: "slip_on_yes",
    category: "relapse",
    hpDamage: 30,
    xpGain: 25,
    hpHeal: 5,
  },
  {
    id: "q3_night_dreams",
    textMale: "Kya kal raat ko sexual ya gande sapne aaye?",
    textFemale: "Kya kal raat ko sexual ya gande sapne aaye?",
    textMaleEn: "Did you have erotic or explicit dreams last night?",
    textFemaleEn: "Did you have erotic or explicit dreams last night?",
    polarity: "slip_on_yes",
    category: "night_urge",
    hpDamage: 10,
    xpGain: 15,
    hpHeal: 5,
  },
  {
    id: "q4_desire_to_watch",
    textMale: "Kya tumhara ganda dekhne ka mann kiya?",
    textFemale: "Kya tumhara ganda dekhne ka mann kiya?",
    textMaleEn: "Did you feel the urge to watch explicit content?",
    textFemaleEn: "Did you feel the urge to watch explicit content?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 15,
    xpGain: 20,
    hpHeal: 5,
  },
  {
    id: "q5_lust_control_now",
    textMale: "Kya tum lust pe control kar pa rahe ho?",
    textFemale: "Kya tum lust pe control kar pa rahi ho?",
    textMaleEn: "Are you successfully controlling your lust?",
    textFemaleEn: "Are you successfully controlling your lust?",
    polarity: "win_on_yes",
    category: "control_win",
    hpDamage: 25,
    xpGain: 35,
    hpHeal: 12,
  },
  {
    id: "q6_inappropriate_seen",
    textMale: "Kya aapne aaj kuch sexual ya inappropriate dekha?",
    textFemale: "Kya aapne aaj kuch sexual ya inappropriate dekha?",
    textMaleEn: "Did you come across anything sexual or inappropriate today?",
    textFemaleEn: "Did you come across anything sexual or inappropriate today?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 20,
    xpGain: 20,
    hpHeal: 5,
  },
  {
    id: "q7_sexual_content_desire",
    textMale: "Kya aaj aapka sexual content dekhne ka mann hua?",
    textFemale: "Kya aaj aapka sexual content dekhne ka mann hua?",
    textMaleEn: "Did you feel an urge to consume sexual content today?",
    textFemaleEn: "Did you feel an urge to consume sexual content today?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 15,
    xpGain: 20,
    hpHeal: 5,
  },
  {
    id: "q8_controlling_urges_status",
    textMale: "Kya aap apni sexual urges par control kar pa rahe hain?",
    textFemale: "Kya aap apni sexual urges par control kar pa rahi hain?",
    textMaleEn: "Are you maintaining control over your sexual urges?",
    textFemaleEn: "Are you maintaining control over your sexual urges?",
    polarity: "win_on_yes",
    category: "control_win",
    hpDamage: 25,
    xpGain: 35,
    hpHeal: 10,
  },
  {
    id: "q9_masturbation_urge_felt",
    textMale: "Kya aaj aapko masturbation karne ka urge hua?",
    textFemale: "Kya aaj aapko masturbation karne ka urge hua?",
    textMaleEn: "Did you experience an urge to masturbate today?",
    textFemaleEn: "Did you experience an urge to masturbate today?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 12,
    xpGain: 20,
    hpHeal: 5,
  },
  {
    id: "q10_deliberate_fantasies",
    textMale: "Kya aapne aaj jaan-bujhkar sexual thoughts ko continue kiya?",
    textFemale: "Kya aapne aaj jaan-bujhkar sexual thoughts ko continue kiya?",
    textMaleEn: "Did you deliberately entertain sexual thoughts today?",
    textFemaleEn: "Did you deliberately entertain sexual thoughts today?",
    polarity: "slip_on_yes",
    category: "relapse",
    hpDamage: 25,
    xpGain: 25,
    hpHeal: 8,
  },
  {
    id: "q11_aroused_by_content",
    textMale: "Kya aapne aaj koi aisa content dekha jisse sexually aroused huye?",
    textFemale: "Kya aapne aaj koi aisa content dekha jisse sexually aroused hui?",
    textMaleEn: "Did you view any content that triggered sexual arousal today?",
    textFemaleEn: "Did you view any content that triggered sexual arousal today?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 20,
    xpGain: 20,
    hpHeal: 5,
  },
  {
    id: "q12_night_sleep_disturbed",
    textMale: "Kya aapko raat mein sexual thoughts ki wajah se neend disturb hui?",
    textFemale: "Kya aapko raat mein sexual thoughts ki wajah se neend disturb hui?",
    textMaleEn: "Was your sleep disturbed by sexual thoughts last night?",
    textFemaleEn: "Was your sleep disturbed by sexual thoughts last night?",
    polarity: "slip_on_yes",
    category: "night_urge",
    hpDamage: 15,
    xpGain: 15,
    hpHeal: 5,
  },
  {
    id: "q13_effort_to_control",
    textMale: "Kya aapne aaj apne urge ko control karne ki koshish ki?",
    textFemale: "Kya aapne aaj apne urge ko control karne ki koshish ki?",
    textMaleEn: "Did you actively make an effort to conquer your urges today?",
    textFemaleEn: "Did you actively make an effort to conquer your urges today?",
    polarity: "win_on_yes",
    category: "control_win",
    hpDamage: 15,
    xpGain: 30,
    hpHeal: 12,
  },
  {
    id: "q14_urge_higher_than_normal",
    textMale: "Kya aapko lagta hai ki aaj aapka sexual urge normal se zyada tha?",
    textFemale: "Kya aapko lagta hai ki aaj aapka sexual urge normal se zyada tha?",
    textMaleEn: "Did you feel your sexual urge was stronger than usual today?",
    textFemaleEn: "Did you feel your sexual urge was stronger than usual today?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 10,
    xpGain: 20,
    hpHeal: 5,
  },
  {
    id: "q15_searched_sexual_content",
    textMale: "Kya aapne aaj sexual content internet par search kiya?",
    textFemale: "Kya aapne aaj sexual content internet par search kiya?",
    textMaleEn: "Did you search for explicit or sexual content online today?",
    textFemaleEn: "Did you search for explicit or sexual content online today?",
    polarity: "slip_on_yes",
    category: "relapse",
    hpDamage: 35,
    xpGain: 30,
    hpHeal: 8,
  },
  {
    id: "q16_repeating_intrusive_thoughts",
    textMale: "Kya aapko baar-baar sexual thoughts aa rahe the?",
    textFemale: "Kya aapko baar-baar sexual thoughts aa rahe the?",
    textMaleEn: "Were you bothered by repeated intrusive sexual thoughts?",
    textFemaleEn: "Were you bothered by repeated intrusive sexual thoughts?",
    polarity: "slip_on_yes",
    category: "trigger",
    hpDamage: 12,
    xpGain: 15,
    hpHeal: 5,
  },
  {
    id: "q17_avoided_triggers",
    textMale: "Kya aapne aaj apne aap ko kisi sexual trigger se door rakha?",
    textFemale: "Kya aapne aaj apne aap ko kisi sexual trigger se door rakha?",
    textMaleEn: "Did you actively steer clear of sexual triggers today?",
    textFemaleEn: "Did you actively steer clear of sexual triggers today?",
    polarity: "win_on_yes",
    category: "control_win",
    hpDamage: 15,
    xpGain: 35,
    hpHeal: 15,
  },
  {
    id: "q18_better_control_mindset",
    textMale: "Kya aapko lagta hai ki aap apne urges ko pehle se better control kar rahe hain?",
    textFemale: "Kya aapko lagta hai ki aap apne urges ko pehle se better control kar rahi hain?",
    textMaleEn: "Do you feel your self-control over urges is improving?",
    textFemaleEn: "Do you feel your self-control over urges is improving?",
    polarity: "win_on_yes",
    category: "control_win",
    hpDamage: 15,
    xpGain: 40,
    hpHeal: 15,
  },
  {
    id: "q19_discipline_emergency_action",
    textMale: "Kya urge aane par Cold Shower, Pushups, ya Running ki?",
    textFemale: "Kya urge aane par Cold Shower, Workout, ya Walking ki?",
    textMaleEn: "Did you take emergency action (Cold Shower, Pushups, Sprint) when urge struck?",
    textFemaleEn: "Did you take emergency action (Cold Shower, Workout, Walk) when urge struck?",
    polarity: "win_on_yes",
    category: "habit_boost",
    hpDamage: 0,
    xpGain: 45,
    hpHeal: 20,
  },
  {
    id: "q20_meditation_mindfulness",
    textMale: "Kya aapne aaj 5-10 minute mindful breathing ya meditation kiya?",
    textFemale: "Kya aapne aaj 5-10 minute mindful breathing ya meditation kiya?",
    textMaleEn: "Did you practice 5-10 minutes of mindful breathing or meditation today?",
    textFemaleEn: "Did you practice 5-10 minutes of mindful breathing or meditation today?",
    polarity: "win_on_yes",
    category: "habit_boost",
    hpDamage: 0,
    xpGain: 40,
    hpHeal: 15,
  },
];
