import { StoreItem } from "@/types/game";

export const STORE_ITEMS: StoreItem[] = [
  // ==========================================
  // 1. CONSUMABLES & HEALTH RESTORATION
  // ==========================================
  {
    id: "zen_tea",
    name: "Oolong Lotus Brew",
    category: "potion",
    cost: 20,
    minLevel: 1,
    icon: "🍵",
    description: "Soothing hot brew of lotus blossoms. Calms hyperactive dopamine receptors after a stressful afternoon.",
    benefit: "+20 HP Vitality",
    isConsumable: true,
    badge: "Starter",
    effectType: "heal_hp",
    effectValue: 20,
  },
  {
    id: "smoke_bomb",
    name: "Ninja Urge Smoke Bomb",
    category: "potion",
    cost: 25,
    minLevel: 1,
    icon: "💨",
    description: "Disorient craving triggers instantly. Vanish from impulsive dopamine spikes and soothe your nervous system.",
    benefit: "+15 HP & Zen Calm",
    isConsumable: true,
    badge: "Panic Item",
    effectType: "smoke_bomb",
    effectValue: 15,
  },
  {
    id: "potion_hp",
    name: "Phoenix Vitality Elixir",
    category: "potion",
    cost: 35,
    minLevel: 1,
    icon: "🧪",
    description: "Brewed from pure discipline flames. Restores willpower vitality after difficult days.",
    benefit: "+35 HP Vitality",
    isConsumable: true,
    badge: "Essential",
    effectType: "heal_hp",
    effectValue: 35,
  },
  {
    id: "holy_water_tears",
    name: "Saint's Tear of Purification",
    category: "potion",
    cost: 50,
    minLevel: 3,
    icon: "💧",
    description: "Sacred crystal droplets that dissolve guilty thoughts and restore mental clarity.",
    benefit: "+40 HP Vitality",
    isConsumable: true,
    badge: "Purity",
    effectType: "heal_hp",
    effectValue: 40,
  },
  {
    id: "chakra_surge_tincture",
    name: "Kyuubi Chakra Tonic",
    category: "potion",
    cost: 70,
    minLevel: 8,
    icon: "🍶",
    description: "Taps into hidden reserves of fiery chakra. Rapidly re-energizes depleted spiritual stamina.",
    benefit: "+60 HP Vitality",
    isConsumable: true,
    badge: "Potent",
    effectType: "heal_hp",
    effectValue: 60,
  },
  {
    id: "potion_mega_hp",
    name: "Senzu Willpower Bean",
    category: "potion",
    cost: 90,
    minLevel: 5,
    icon: "🫘",
    description: "Korin's legendary divine bean. Immediately restores your HP to absolute maximum 100% capacity.",
    benefit: "Full 100% Max HP",
    isConsumable: true,
    badge: "Dragon Ball",
    effectType: "heal_hp",
    effectValue: 100,
  },
  {
    id: "revive_feather",
    name: "Phoenix Rebirth Feather",
    category: "potion",
    cost: 220,
    minLevel: 10,
    icon: "🪶",
    description: "Burn from the ashes! If you suffer Game Over, this feather auto-revives you with 50% HP without resetting streak.",
    benefit: "Auto-Revive (50% HP)",
    isConsumable: true,
    badge: "Revival Relic",
    effectType: "revive_hp",
    effectValue: 50,
  },
  {
    id: "revive_elixir",
    name: "Revive Elixir",
    category: "potion",
    cost: 250,
    minLevel: 10,
    icon: "🏺",
    description: "The ultimate emergency antidote. If a daily check-in is missed and the fatal 10-second countdown activates, consuming this elixir halts the countdown, saves your entire account progress from resetting to Level 1, and restores your HP to full 100% capacity.",
    benefit: "Cancels 10s Missed Day Reset & Full HP",
    isConsumable: true,
    badge: "Every 10th Level",
    effectType: "revive_elixir",
    effectValue: 100,
  },
  {
    id: "revive_stone",
    name: "Philosopher's Will Stone",
    category: "potion",
    cost: 380,
    minLevel: 18,
    icon: "💎",
    description: "The apex alchemical artifact. Revives the fallen warrior with 100% Full HP and grants 1 Free Streak Shield.",
    benefit: "Full Revive + Shield",
    isConsumable: true,
    badge: "Mythic Relic",
    effectType: "revive_hp",
    effectValue: 100,
  },

  // ==========================================
  // 2. SHIELDS & DEFENSE
  // ==========================================
  {
    id: "streak_shield",
    name: "Aegis Streak Shield",
    category: "shield",
    cost: 75,
    minLevel: 1,
    icon: "🛡️",
    description: "Celestial shield. If you miss a 12:00 AM midnight cutoff, 1 shield auto-activates to protect your streak!",
    benefit: "Streak Freeze (1 Day)",
    isConsumable: true,
    badge: "Must-Have",
    effectType: "streak_shield",
    effectValue: 1,
  },
  {
    id: "kamui_talisman",
    name: "Kamui Phase Talisman",
    category: "shield",
    cost: 110,
    minLevel: 9,
    icon: "🌀",
    description: "Phase into a pocket dimension when high-risk craving situations arise. Restores 25 HP and adds 1 Shield.",
    benefit: "+25 HP & +1 Shield",
    isConsumable: true,
    badge: "Uchiha Jutsu",
    effectType: "streak_shield",
    effectValue: 1,
  },
  {
    id: "grand_aegis_shield",
    name: "Mirror of Yata",
    category: "shield",
    cost: 190,
    minLevel: 12,
    icon: "🪞",
    description: "Sacred mirror imbued with absolute defense. Grants 3 consecutive days of streak freeze protection.",
    benefit: "Streak Freeze (3 Days)",
    isConsumable: true,
    badge: "Triple Guard",
    effectType: "streak_shield",
    effectValue: 3,
  },
  {
    id: "susanoo_ribcage",
    name: "Susano'o Ribcage Barrier",
    category: "shield",
    cost: 230,
    minLevel: 14,
    icon: "💀",
    description: "Manifest an ethereal chakra ribcage. Protects against 2 missed days and restores 30 HP instantly.",
    benefit: "2 Shields + 30 HP",
    isConsumable: true,
    badge: "Mangekyo",
    effectType: "streak_shield",
    effectValue: 2,
  },
  {
    id: "infinity_barrier",
    name: "Gojo's Limitless Veil",
    category: "shield",
    cost: 290,
    minLevel: 16,
    icon: "🌌",
    description: "The closer urges come to touching you, the slower they move. Infinite protection for 4 missed streak cutoffs.",
    benefit: "Streak Freeze (4 Days)",
    isConsumable: true,
    badge: "Special Grade",
    effectType: "streak_shield",
    effectValue: 4,
  },

  // ==========================================
  // 3. XP BOOSTERS & FAST PROGRESSION
  // ==========================================
  {
    id: "booster_xp",
    name: "Divine Chakra Capsule",
    category: "booster",
    cost: 45,
    minLevel: 1,
    icon: "💊",
    description: "Concentrated ninja training essence. Injects instant willpower experience to accelerate your next level.",
    benefit: "+100 Instant XP",
    isConsumable: true,
    badge: "Fast Level",
    effectType: "gain_xp",
    effectValue: 100,
  },
  {
    id: "double_xp",
    name: "Scroll of Twin Flow",
    category: "booster",
    cost: 60,
    minLevel: 1,
    icon: "⚡",
    description: "Enter the deep zone of twin flow. All XP earned from daily logs is doubled for the next 2 days.",
    benefit: "2x XP Multiplier (2 Days)",
    isConsumable: true,
    badge: "2X XP",
    effectType: "double_xp",
    effectValue: 2,
  },
  {
    id: "booster_hyper_xp",
    name: "Hyperbolic Time Capsule",
    category: "booster",
    cost: 120,
    minLevel: 7,
    icon: "⏳",
    description: "Compress one full year of solitary discipline into a single second. Massive instant XP explosion!",
    benefit: "+300 Instant XP",
    isConsumable: true,
    badge: "300 XP",
    effectType: "gain_xp",
    effectValue: 300,
  },
  {
    id: "zenitsu_thunder_clap",
    name: "Thunderclap First Form Scroll",
    category: "booster",
    cost: 140,
    minLevel: 13,
    icon: "⚡",
    description: "Unleash Hekireki Issen! Strike cravings at the speed of lightning for instant surge of XP and HP.",
    benefit: "+200 XP & +15 HP",
    isConsumable: true,
    badge: "Demon Slayer",
    effectType: "gain_xp",
    effectValue: 200,
  },
  {
    id: "triple_xp",
    name: "Ancient Sage Tome",
    category: "booster",
    cost: 180,
    minLevel: 15,
    icon: "📜",
    description: "Mount Myoboku's forbidden scroll. Triples all discipline XP earned across the next 3 days!",
    benefit: "3x XP Multiplier (3 Days)",
    isConsumable: true,
    badge: "Sage Boost",
    effectType: "double_xp",
    effectValue: 3,
  },

  // ==========================================
  // 4. USER SPECIFIED MAJOR ITEMS (LEVEL 20, 22, 25)
  // ==========================================
  {
    id: "item_surpass_2_levels",
    name: "Heaven's Scroll: Surpass 2 Levels",
    category: "booster",
    cost: 450,
    minLevel: 20, // Requirement 1: Level 20+ item to skip 2 levels
    icon: "🌟",
    description: "Ancient forbidden scroll unlocked only by veteran masters at Level 20+. Instantly surpasses 2 full levels!",
    benefit: "Skip +2 Full Levels Instantly",
    isConsumable: true,
    badge: "Level 20+ Exclusive",
    effectType: "surpass_levels",
    effectValue: 2,
  },
  {
    id: "item_skill_respec",
    name: "Elemental Respec Soul Orb",
    category: "booster",
    cost: 350,
    minLevel: 22, // Requirement 3: Level 22+ item for one-time skill change
    icon: "🔮",
    description: "Resonates with cosmic elements. Allows a seasoned warrior of Level 22+ to change their Elemental Skill class!",
    benefit: "One-Time Skill Change",
    isConsumable: true,
    badge: "Level 22+ Exclusive",
    effectType: "change_skill",
    effectValue: "respec",
  },
  {
    id: "item_attack_guild",
    name: "Death Note: Guild Mate Strike",
    category: "booster",
    cost: 550,
    minLevel: 25, // Requirement 2: Level 25+ item to attack guild mate & slash XP
    icon: "📓",
    description: "Write the name of a guild mate to unleash an untraceable strike that slashes 250 XP from their current rank!",
    benefit: "Slash Guild Mate XP (-250 XP)",
    isConsumable: true,
    badge: "Level 25+ PvP Strike",
    effectType: "attack_guild_mate",
    effectValue: 250,
  },
  {
    id: "item_chakra_drain",
    name: "Rasengan Chakra Siphon",
    category: "booster",
    cost: 320,
    minLevel: 18,
    icon: "🌀",
    description: "Siphon spiritual momentum from rival clan reserves to boost your own personal coin treasury.",
    benefit: "Steal +120 Bonus Coins",
    isConsumable: true,
    badge: "Coin Heist",
    effectType: "gain_xp",
    effectValue: 150,
  },
  {
    id: "item_curse_doll",
    name: "Straw Doll Resonance Nail",
    category: "booster",
    cost: 280,
    minLevel: 24,
    icon: "🔨",
    description: "Nobara's resonance technique. Sends shockwaves of accountability to wake up slacking guild comrades.",
    benefit: "+180 Instant XP",
    isConsumable: true,
    badge: "Jujutsu Relic",
    effectType: "gain_xp",
    effectValue: 180,
  },

  // ==========================================
  // 5. AVATAR AURAS (COSMETIC EQUIP)
  // ==========================================
  {
    id: "aura_solar_flare",
    name: "Solar Flare Aura",
    category: "aura",
    cost: 80,
    minLevel: 1,
    icon: "🔥",
    description: "Golden solar flames pulse around your avatar frame across the top navigation and profile deck.",
    benefit: "Fiery Avatar Glow",
    isConsumable: false,
    badge: "Flame Visual",
    effectType: "equip_aura",
    effectValue: "solar_flare",
  },
  {
    id: "aura_glacial_frost",
    name: "Glacial Frost Aura",
    category: "aura",
    cost: 80,
    minLevel: 1,
    icon: "❄️",
    description: "Sub-zero crystalline diamond frost sparkles around your avatar, representing ice-cold composure.",
    benefit: "Ice Crystal Frame",
    isConsumable: false,
    badge: "Frost Visual",
    effectType: "equip_aura",
    effectValue: "glacial_frost",
  },
  {
    id: "aura_sage_mode",
    name: "Toad Sage Vermilion Aura",
    category: "aura",
    cost: 180,
    minLevel: 11,
    icon: "🐸",
    description: "Natural energy markings illuminate your portrait with orange sage pigment and mountain chakra.",
    benefit: "Sage Nature Glow",
    isConsumable: false,
    badge: "Sage Visual",
    effectType: "equip_aura",
    effectValue: "sage_mode",
  },
  {
    id: "aura_ultra_instinct",
    name: "Ultra Instinct Silver Radiance",
    category: "aura",
    cost: 260,
    minLevel: 15,
    icon: "✨",
    description: "Gleaming silver waves of godlike instinct envelop your profile. Total autonomy over mortal impulses.",
    benefit: "Divine Silver Flare",
    isConsumable: false,
    badge: "Divine Visual",
    effectType: "equip_aura",
    effectValue: "ultra_instinct",
  },
  {
    id: "aura_cursed_energy",
    name: "Sukuna's Malevolent Sparks",
    category: "aura",
    cost: 320,
    minLevel: 20,
    icon: "🩸",
    description: "Dark crimson black sparks crackle violently around your card. Intimidates all who view your profile.",
    benefit: "Blood Crimson Sparks",
    isConsumable: false,
    badge: "King of Curses",
    effectType: "equip_aura",
    effectValue: "cursed_energy",
  },
  {
    id: "aura_bankai_shadow",
    name: "Tensa Zangetsu Void Cloak",
    category: "aura",
    cost: 360,
    minLevel: 23,
    icon: "🗡️",
    description: "Jet-black swirling spiritual reiatsu folds around your portrait like a shinigami bankai coat.",
    benefit: "Black Reiatsu Cloak",
    isConsumable: false,
    badge: "Bankai Visual",
    effectType: "equip_aura",
    effectValue: "bankai_shadow",
  },
  {
    id: "aura_gear_5",
    name: "Sun God Nika Drum Ribbon",
    category: "aura",
    cost: 420,
    minLevel: 28,
    icon: "🥁",
    description: "The drums of liberation! Whimsical pure-white heavenly cloud scarf floating around your avatar.",
    benefit: "White Cloud Ribbon",
    isConsumable: false,
    badge: "Mythical Zoan",
    effectType: "equip_aura",
    effectValue: "gear_5",
  },

  // ==========================================
  // 6. LEGENDARY TITLES (EQUIPPABLE HONOR)
  // ==========================================
  {
    id: "title_shadow_monarch",
    name: "Title: Shadow Monarch",
    category: "title",
    cost: 110,
    minLevel: 5,
    icon: "👑",
    description: "'Arise!' Command absolute dominion over urges like Sung Jin-Woo commanding immortal shadow soldiers.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "Solo Leveling",
    effectType: "equip_title",
    effectValue: "Shadow Monarch of Willpower",
  },
  {
    id: "title_domain_expander",
    name: "Title: Domain Expander",
    category: "title",
    cost: 130,
    minLevel: 8,
    icon: "⛩️",
    description: "'Ryōiki Tenkai: Infinite Clean Streak'. Inside your domain, low-grade desires cease to exist.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "Jujutsu Kaisen",
    effectType: "equip_title",
    effectValue: "Domain Expander: Infinite Clean",
  },
  {
    id: "title_hashira",
    name: "Title: Flame Hashira",
    category: "title",
    cost: 150,
    minLevel: 10,
    icon: "🗡️",
    description: "'Set your heart ablaze!' Stand steadfast before the darkness of temptation without flinching.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "Demon Slayer",
    effectType: "equip_title",
    effectValue: "Flame Hashira of Discipline",
  },
  {
    id: "title_hokage",
    name: "Title: Seventh Hokage",
    category: "title",
    cost: 250,
    minLevel: 17,
    icon: "🍃",
    description: "Protecting the entire village starts with conquering yourself. A legendary willpower leader.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "Naruto",
    effectType: "equip_title",
    effectValue: "The Willpower Hokage",
  },
  {
    id: "title_yonko",
    name: "Title: Emperor of the Pure Sea",
    category: "title",
    cost: 380,
    minLevel: 26,
    icon: "🏴‍☠️",
    description: "Command the four corners of the grand line. Only legendary disciplined pirates hold this title.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "One Piece",
    effectType: "equip_title",
    effectValue: "Emperor of the Pure Sea",
  },
  {
    id: "title_zen_master",
    name: "Title: Enlightened Bodhisattva",
    category: "title",
    cost: 420,
    minLevel: 30,
    icon: "🧘",
    description: "Beyond attachment, beyond craving, beyond regret. The mind rests in crystalline eternal stillness.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "Zen Master",
    effectType: "equip_title",
    effectValue: "Enlightened Bodhisattva",
  },
  {
    id: "title_god_of_highschool",
    name: "Title: Monkey King Reborn",
    category: "title",
    cost: 500,
    minLevel: 35,
    icon: "🐵",
    description: "Wielder of the Ruyi Jingu Bang. Overcame heaven, hell, and mortal lust through raw godly strength.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "God Tier",
    effectType: "equip_title",
    effectValue: "The Great Sage Monkey King",
  },
  {
    id: "title_untouchable",
    name: "Title: The Untouchable Ascetic",
    category: "title",
    cost: 650,
    minLevel: 40,
    icon: "🌌",
    description: "The apex of human self-mastery at Level 40. Relapse is an impossibility in your reality.",
    benefit: "Equippable Title",
    isConsumable: false,
    badge: "Level 40 Pinnacle",
    effectType: "equip_title",
    effectValue: "The Untouchable Ascetic",
  },

  // ==========================================
  // 7. ANIME ARTIFACTS & EMERGENCY ITEMS
  // ==========================================
  {
    id: "item_genjutsu_breaker",
    name: "Genjutsu Dispel Bell",
    category: "potion",
    cost: 85,
    minLevel: 6,
    icon: "🔔",
    description: "A single ring disrupts fake sensory hallucinations and restores conscious cognitive control.",
    benefit: "+25 HP & Mental Clarity",
    isConsumable: true,
    badge: "Anti-Illusion",
    effectType: "heal_hp",
    effectValue: 25,
  },
  {
    id: "item_behelit_resolve",
    name: "Crimson Behelit of Pure Resolve",
    category: "potion",
    cost: 480,
    minLevel: 32,
    icon: "🥚",
    description: "Forged in destiny's crucible. In your darkest hour, cry out to gain +50 HP and +200 instant XP.",
    benefit: "+50 HP & +200 XP",
    isConsumable: true,
    badge: "Eclipse Artifact",
    effectType: "heal_hp",
    effectValue: 50,
  },

  // ==========================================
  // 8. PREMIUM MUSIC STUDIO MASTERS (STORE EXCLUSIVE, >1500 COINS)
  // ==========================================
  {
    id: "premium_midnight_rain_pre",
    name: "Premium Song: Midnight Rain (Studio Master)",
    category: "music",
    cost: 1500, // User Requirement: Premium song in store, > 1500 coins
    minLevel: 1,
    icon: "🎵",
    description: "Full studio master recording of Midnight Rain. Unlocks permanently in your Arena Jukebox forever.",
    benefit: "Permanent Arena Jukebox Song",
    isConsumable: false,
    badge: "1500 Coins Elite",
    effectType: "unlock_premium_song",
    effectValue: "premium_midnight_rain_pre",
  },
  {
    id: "premium_warriors_ascent_pre",
    name: "Premium Song: Warrior's Ascent (Epic Master)",
    category: "music",
    cost: 1800, // User Requirement: Premium song in store, > 1500 coins
    minLevel: 1,
    icon: "⚡",
    description: "Mythic orchestral battle score for legendary streaks. Unlocks permanently across all game views.",
    benefit: "Permanent Arena Jukebox Song",
    isConsumable: false,
    badge: "1800 Coins Mythic",
    effectType: "unlock_premium_song",
    effectValue: "premium_warriors_ascent_pre",
  },

  // ==========================================
  // 9. LEVEL 30 MASTERY MILESTONE (NAME REFORGE SCROLL)
  // ==========================================
  {
    id: "item_username_respec_lvl30",
    name: "Master's Identity Reforge Scroll",
    category: "relic",
    cost: 100,
    minLevel: 30,
    icon: "📜",
    description: "Sacred parchment bestowed upon warriors reaching Level 30. Unlocks an exclusive opportunity to change your permanent @username handle once more.",
    benefit: "+1 Username Change Opportunity",
    isConsumable: true,
    badge: "Level 30 Milestone",
    effectType: "unlock_username_change",
    effectValue: 1,
  },
];
